version: '3'

dotenv: ['.env']

tasks:
  default:
    cmds:
      - echo "This is task cmd"
    silent: true
  
  build:
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -o bin/main cmd/main.go
    silent: true
  run:
    cmds:
      - ./bin/main
    deps:
      - build
    silent: true

  build-mage:
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -o ./mage mage-tools/mage.go
    silent: true
  
  build-gg:
    cmds:
      - ./mage -d mage-tools -compile ../gg
    deps:
      - build-mage
    silent: true

  coverage:
    cmds:
      - go test -v -cover ./...
    silent: true
  test:
    cmds:
      - go test -v ./...
    silent: true
  
  db_login:
    cmds:
      - psql $DB_URL
    silent: true
  
  db_create_migration:
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.table_name}}
    silent: true
    requires:
      vars: [table_name]

  db_migrate:
    cmds:
      - migrate -database $DB_URL -path migrations {{.action}}
    silent: true
    requires:
      vars: [action]
    ## action should be up or down
  
  test_db_migrate:
    cmds:
      - migrate -database $DB_URL_TEST -path migrations {{.action}}
    silent: true
    requires:
      vars: [action]
 
  test_db_login:
    cmds:
      - psql $DB_URL_TEST
    silent: true